apiVersion: cluster.x-k8s.io/v1beta2
kind: Cluster
metadata:
  name: ${CLUSTER_NAME}
spec:
  topology:
    classRef:
      name: dev-test
    controlPlane:
      replicas: ${CONTROL_PLANE_MACHINE_COUNT}
    variables:
    - name: identityRef
      value:
        cloudName: ${OPENSTACK_CLOUD:=capo-e2e}
        name: ${CLOUD_CONFIG_SECRET:=dev-test-cloud-config}
    - name: imageRef
      value: ${IMAGE_REF:=node-image}
    - name: addImageVersion
      value: ${ADD_IMAGE_VERSION:=false}
    - name: injectIgnitionSysext
      value: ${INJECT_IGNITION_SYSEXT:=true}
    - name: allowedCIDRs
      value: ${OPENSTACK_API_SERVER_ALLOWED_CIDRS:=[]}
    - name: bastion
      value:
        enabled: ${OPENSTACK_BASTION_ENABLED:=false}
        spec:
          flavor: ${OPENSTACK_BASTION_FLAVOR:=m1.small}
          image:
            imageRef:
              name: ${OPENSTACK_BASTION_IMAGE_NAME:=ubuntu-24.04}
          sshKeyName: ${OPENSTACK_SSH_KEY_NAME:=""}
    version: ${KUBERNETES_VERSION}
    workers:
      machineDeployments:
      - class: default-worker
        name: md-0
        replicas: ${WORKER_MACHINE_COUNT}
